Actions Tools (#1)

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -62,10 +62,18 @@ jobs:
             status: broken
             by: ralf
 
-      #- name: "Validate Outputs"
-      #  run: |
-      #    echo "sha: '${{ steps.test.outputs.sha }}'"
-      #    if [ -z '${{ steps.test.outputs.sha }}' ];then
-      #      echo "No Output: sha"
-      #      exit 1
-      #    fi
+      - name: "Validate Outputs"
+        if: ${{ !github.event.act }}
+        env:
+          sha: ${{ steps.test.outputs.sha }}
+        run: |
+          echo "sha: ${sha}"
+          if [ -z "${sha}" ];then
+            echo "No Output: sha"
+            exit 1
+          fi
+          echo "GITHUB_SHA: ${GITHUB_SHA}"
+          if [ "${sha}" != "${GITHUB_SHA}" ];then
+            echo "Invalid Output: sha"
+            exit 1
+          fi
